import { SchoolProfile } from '../types';

declare global {
  interface Window {
    jspdf: any;
  }
}

// A4 dimensions in mm
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 14;

const addHeader = (doc: any, profile: SchoolProfile) => {
    if (profile.logoUrl) {
        try {
            doc.addImage(profile.logoUrl, 'PNG', MARGIN, MARGIN, 20, 20);
        } catch(e) {
            console.error("Error adding logo to PDF:", e);
        }
    }
    
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(profile.name, PAGE_WIDTH / 2, MARGIN + 8, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(profile.address, PAGE_WIDTH / 2, MARGIN + 15, { align: 'center' });
};

const addFooter = (doc: any) => {
    const pageCount = doc.internal.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(150);
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 10, { align: 'center' });
        doc.text(`Generated by School ERP System | ${new Date().toLocaleDateString()}`, MARGIN, PAGE_HEIGHT - 10);
    }
};

export const generatePdfWithBranding = (
    profile: SchoolProfile,
    title: string,
    autoTableConfig: { head: any[][], body: any[][], [key: string]: any },
    fileName: string
) => {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    addHeader(doc, profile);
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40);
    doc.text(title, MARGIN, MARGIN + 40);

    doc.autoTable({
        startY: MARGIN + 45,
        theme: 'grid',
        headStyles: { fillColor: [37, 99, 235] },
        ...autoTableConfig,
    });
    
    addFooter(doc);

    doc.save(fileName);
};